name: Build an Arbitrum Stylus Dev Docker Image

on: workflow_dispatch

env:
  REGISTRY: ghcr.io
  NAMESPACE: ${{ github.repository_owner }}
  IMAGE_NAME: nitro-stylus-devnet

jobs:
  build-nitro-docker-image:
    name: Build Nitro Stylus Docker Image
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      actions: write
    outputs:
      digest: ${{ steps.build.outputs.digest }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          repository: OffchainLabs/nitro-devnode
          submodules: recursive

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2.2.1

      - name: Log in to the Container registry
        uses: docker/login-action@v2.1.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        id: meta_nitro_dev
        uses: docker/metadata-action@v4
        with:
          # list of Docker images to use as base name for tags
          images: |
            ${{ env.REGISTRY }}/${{ env.NAMESPACE }}/${{ env.IMAGE_NAME }}
          # generate Docker tags based on the following events/attributes
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha

      - name: Build and push
        id: build
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64, linux/arm64
          file: stylus-dev/Dockerfile
          build-args: |
            GOFLAGS=-tags=2k
          push: true
          tags: ${{ steps.meta_stylus_dev.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
